name: business-grpc-module
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=
  - colorama=0.*
  - numpy=1.*
  - pandas=1.*
  - geopy=2.*
  - urllib3=1.*
  - beautifulsoup4=4*
  - matplotlib=3.*
  - requests=2.*
  - pydantic=1.*
  - jsonpickle=3.*
  - mpld3=0.*
  - numpy-financial=1.*
  - pip:
    - grpcio==1.44.0
    - protobuf==3.20.1
    - python-dotenv==0.20.0